version: "3"

services: 
    nginx:
        image: nginx:stable-alpine
        volumes: 
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        ports: 
            - "5000:80"
    ts-app:
        build: .
        environment: 
            - NODE_PORT=5000
            # loading from .env
            - PG_HOST=${DB_HOST}
            - PG_USER=${DB_USER}
            - PG_PASS=${DB_PW}
            - PG_PORT=${DB_PORT}
            - PG_DB=${DB_NAME}
            - REDIS_URL=${RD_URL}
            - REDIS_PORT=${RD_PORT}
            - SECRET=${SECRET}
        depends_on: 
            - postgres-db
    postgres-db:
        image: postgres:13.2-alpine
        environment:
            POSTGRES_PASSWORD: ${PG_INIT_PASS}
        volumes: 
            - /data:/var/lib/postgresql/data
    redis:
        image: redis:6.2.3-alpine
        volumes: 
            - redis-data:/usr/local/etc/redis

volumes: 
    pg-data:
    redis-data: