version: "3"

services:
    nginx:
        ports:
            - "5000:80"
    ts-app:
        build:
            
            context: .
            args: 
                NODE_ENV: dev
        volumes: 
            - ./:/app
            - /app/node_modules
        environment: 
            - NODE_ENV=dev
        command: yarn run start:dev