version: "3.8"

services: 
    ts-app:
        build: .
        ports: 
            - "5000:5000"
        environment: 
            - NODE_PORT=5000
            # loading from .env
            - PG_HOST=${DB_HOST}
            - PG_USER=${DB_USER}
            - PG_PASS=${DB_PW}
            - PG_PORT=${DB_PORT}
            - PG_DB=${DB_NAME}
        depends_on: 
            - postgres-db
    postgres-db:
        image: postgres:13.2-alpine
        environment:
            POSTGRES_PASSWORD: admin
        volumes: 
            - /data:/var/lib/postgresql/data
volumes: 
    pg-data:
